apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-private
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-private
    app.kubernetes.io/part-of: devfile-sample-go-basic-private
  name: devfile-sample-go-basic-private
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic-private
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic-private
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mfaisal2-tenant/devfile-sample-go-basic-private/devfile-sample-go-basic-private@sha256:282eb61bb1723cb43f954fb1b53f1db76ab56cbe70d47feaaad3314714353e34
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 12m
            memory: 18Mi
status: {}
